source 'git@github.com:tutu-ru-mobile/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'MWPhotoBrowser_Example' do
  pod "MWPhotoBrowser", :path => "../"
end

target 'MWPhotoBrowser_Tests' do
  pod "MWPhotoBrowser", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
